### ISSUE TITLE
Unclear sentence in README

### ISSUE THREAD

**Issue by retog** [linked-solutions/fuseki-auth#3]
The following partial sentence is unclear

> Setup own users login/signup in "Realm Settings" -> "Login"

On the indicated page I don't see an option to setup user login/signup

![image](https://user-images.githubusercontent.com/110756/52575622-cf1a1380-2e1e-11e9-9110-61fbe12da056.png)

**Comment by DrBAXA** [comment]
The first button/checkbox here is to enable registration/signup

**Comment by retog** [comment]
What about replacing the partial sentence with the following:

Enable `User registration` in "Realm Settings" -> "Login"
